server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
    #配置监控页面
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern:
          - "/druid/*"
  thymeleaf:
    cache: false

#mybatis的配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*Mapper.xml

#shiro配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  unauthorized-url: /unauthoried.html
  anon-urls:
    - /index.html*
    - /login.html*
    - /login/toLogin*
    - /login/login*
  logout-url: /login/logout*
  authc-urls:
    - /**
